// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef OI_H
#define OI_H
#include "WPILib.h"
#include "Round.h"
class OI {
private:
	static const double PotRange;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Joystick* m_leftStick;
	Joystick* m_rightStick;
	Joystick* m_gameStick;
	JoystickButton* m_rightTrigger;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	JoystickButton* m_leftTrigger;
	JoystickButton* m_rightButton2;
	JoystickButton* m_rightButton3;
	JoystickButton* m_rightButton4;
	JoystickButton* m_rightButton5;
	JoystickButton* m_rightButton6;
	JoystickButton* m_rightButton7;
	JoystickButton* m_rightButton8;
	JoystickButton* m_rightButton9;
	JoystickButton* m_rightButton10;
	JoystickButton* m_rightButton11;
	JoystickButton* m_leftButton3;
	JoystickButton* m_leftButton4;
	JoystickButton* m_leftButton5;
	JoystickButton* m_leftButton7;
	JoystickButton* m_leftButton8;
	JoystickButton* m_leftButton9;
	JoystickButton* m_leftButton10;
	JoystickButton* m_gameButton1;
	JoystickButton* m_gameButton2;
	JoystickButton* m_gameButton3;
	JoystickButton* m_gameButton4;
	JoystickButton* m_gameButton5;
	JoystickButton* m_gameButton6;
	JoystickButton* m_gameButton7;
	JoystickButton* m_gameButton8;
	DriverStationEnhancedIO* m_enhancedIO;
public:
	enum AutonomousVariant {
		AV_2 = 2,
		AV_4 = 4,
		AV_6 = 6,
		AV_8 = 8,
		AV_NONE = 10
	};
	
	OI();
	DriverStation *station;
	DriverStationLCD *screen;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
	Joystick* getm_rightStick();
	Joystick* getm_leftStick();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
	float getCrouch();
	AutonomousVariant getAutonomousVariant();
	float getCatapultSpeed();
	void printCrouch();
	void printAngle();
	void printVariant();
	void printCatapultSpeed();
	void OI::printTargeting();
	void UpdateScreen();
	
};
#endif
