// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "DriveWithJoysticks.h"
#include "../Robot.h"
DriveWithJoysticks::DriveWithJoysticks() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	Requires(chassis);
}
// Called just before this Command runs the first time
void DriveWithJoysticks::Initialize() {
	printf("DriveWithJoysticks::Initialize()\n");
}
// Called repeatedly when this Command is scheduled to run
void DriveWithJoysticks::Execute() {
	float left = oi->getm_leftStick()->GetY();
	float right = oi->getm_rightStick()->GetY();
	
	chassis->driveWithJoysticks(left*oi->getCrouch(), right*oi->getCrouch());
//	cout << "DriveWithJoysticks::Execute" << endl;
}
// Make this return true when this Command no longer needs to run execute()
bool DriveWithJoysticks::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void DriveWithJoysticks::End() {
	printf("DriveWithJoysticks::End()\n");
}


// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DriveWithJoysticks::Interrupted() {
	printf("DriveWithJoysticks::Interrupted()\n");
}
