// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#ifndef TURNANGLE_H
#define TURNANGLE_H


#include "Commands/Subsystem.h"
#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class TurnAngle: public PIDCommand {
protected:
	virtual double ReturnPIDInput();
	virtual void  UsePIDOutput(double output);
private:
	double m_angle;
	Gyro *m_gryo;
	double m_delta;
	double m_zone_lower;
	double m_zone_higher;
	int m_finished;
	double m_time;
public:
	TurnAngle(double, double, double, double, double, double timout = 0);
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();
	void SetAngle(double angle);
};


#endif
