// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Chassis.h"
#include "../Robotmap.h"
#include "../Commands/DriveWithJoysticks.h"
Chassis::Chassis() : Subsystem("Chassis") {
	m_gyro = new Gyro(MODULE1NUM, CHASSISGYROANALOG);
	m_gyro->SetSensitivity(1.25);
	m_leftMotor = new Talon(MODULE1NUM, CHASSISLEFTMOTORPWM);
	m_rightMotor =  new Talon(MODULE1NUM, CHASSISRIGHTMOTORPWM);
#ifdef	TESTERBOT
	chassisDrive->SetInvertedMotor(RobotDrive::kRearLeftMotor, true);
	chassisDrive->SetInvertedMotor(RobotDrive::kRearRightMotor, true);       
#endif
	drive = new RobotDrive(m_leftMotor, m_rightMotor);
	drive->SetSafetyEnabled(false);
	        drive->SetExpiration(0.1);
	        drive->SetSensitivity(0.5);
	        drive->SetMaxOutput(1.0);
	        
	m_accelrometer = new ADXL345_2489(MODULE1NUM,  0xA6);
}
    
void Chassis::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new DriveWithJoysticks());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
void Chassis::driveWithJoysticks(float rightstick, float leftstick) {
#ifdef TESTERBOT
	drive->TankDrive( leftstick, rightstick);
#else
	drive->TankDrive( rightstick, leftstick);
#endif
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
void Chassis::goStraight(){
	drive->TankDrive(1.0*CommandBase::oi->getCrouch(), 1.0*CommandBase::oi->getCrouch());
}
void Chassis::goBack(){
	drive->TankDrive(-1.0*CommandBase::oi->getCrouch(), -1.0*CommandBase::oi->getCrouch());
}
void Chassis::stop(){
	drive->TankDrive(0*CommandBase::oi->getCrouch(), 0*CommandBase::oi->getCrouch());
}
void Chassis::turnLeft(){
	drive->TankDrive(-1.0*CommandBase::oi->getCrouch(), 1.0*CommandBase::oi->getCrouch());
}
void Chassis::turnRight(){
	drive->TankDrive(1.0*CommandBase::oi->getCrouch(), -1.0*CommandBase::oi->getCrouch());
}
void Chassis::getAccel(){
	double tempx = m_accelrometer->GetAcceleration(ADXL345_2489::kAxis_X);
	double tempy = m_accelrometer->GetAcceleration(ADXL345_2489::kAxis_Y);
	double tempz = m_accelrometer->GetAcceleration(ADXL345_2489::kAxis_Z);
	
	cout << " x1: " << tempx << " ";
	cout << " y2: " << tempy << " ";
	cout << " z1: " << tempz << " ";
}
